INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1, '곡성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (2, '(유)금강장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (3, '(유)신광 익산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (4, '공주의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (5, '곤지암농협장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (6, '(유)예수병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (7, '곤지암장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (8, '(복)대구가톨릭사회복지회논공 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (9, '(유)우석개발');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (10, '(유)은파장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (11, '(유)익산팔봉장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (12, '(유)한솔장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (13, '공도장례식장(영화원)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (14, '(의)동재의료재단오차드장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (15, '(재)하늘가장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (16, '고은장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (17, '(주) 비이케이더블유 좋은장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (18, '관산정남진장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (19, '(주) 비케이더블유 좋은강안병원지점');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (20, '(주)광양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (21, '관인농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (22, '(주)광주국빈장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (23, '광명성애병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (24, '(주)구례장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (25, '공주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (26, '(주)금성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (27, '광양우리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (28, '(주)기흥장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (29, '광양백운장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (30, '(주)디엑스앤브이엑스 제천지점 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (31, '광양서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (32, '(주)모악장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (33, '광주남문장례식장(주)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (34, '고흥봉황장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (35, '곡성섬진장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (36, '광주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (37, '광주보훈병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (38, '광주보람장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (39, '광주수완장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (40, '삼목장례프리드');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (41, '삼성서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (42, '삼성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (43, '삼성장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (44, '삼성창원병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (45, '삼성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (46, '삼신전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (47, '삼육병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (48, '삼육서울병원 추모관(구위생병원)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (49, '삼일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (50, '삼천포서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (51, '삼척의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (52, '삼천포장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (53, '상주성모병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (54, '상주시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (55, '상주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (56, '새고창장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (57, '새금산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (58, '새로운장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (59, '새롬병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (60, '새마을장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (61, '새소망병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (62, '새만금장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (63, '새미소요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (64, '새진교장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (65, '새웅상요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (66, '새천년장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (67, '새통영병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (68, '샘안양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (69, '서귀포의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (70, '서논산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (71, '서부산시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (72, '서산의료원상례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (73, '새동산병원 장례식장(구 365병원장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (74, '서안동농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (75, '서요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (76, '서세종농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (77, '서울대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (78, '서산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (79, '서석장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (80, '서울백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (81, '서울산국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (82, '서울성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (83, '서울아산병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (84, '서울적십자병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (85, '서울좋은병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (86, '서울특별시 동부병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (87, '서울특별시 서울의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (88, '서울특별시보라매병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (89, '서울현대요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (90, '서정리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (91, '서해안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (92, '서천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (93, '서해장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (94, '석곡농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (95, '선산 국화원 전문 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (96, '서천한국장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (97, '선산전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (98, '성가롤로병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (99, '성남시의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (100, '성남시장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (101, '성남중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (102, '성누가병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (103, '성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (104, '성민병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (105, '성모병원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (106, '성빈센트병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (107, '성산현대요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (108, '성서병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (109, '성서요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (110, '성심요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (111, '성심장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (112, '성요한병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (113, '성월장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (114, '성제장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (115, '성주효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (116, '성혜원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (117, '성주국화원전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (118, '세광병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (119, '세명병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (120, '세민병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (121, '세안종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (122, '세민에스백합원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (123, '세웅병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (124, '세인트병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (125, '성애장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (126, '세종병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (127, '세종여주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (128, '세종충남대학교병원 쉴낙원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (129, '센트럴병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (130, '소망장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (131, '속초동해장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (132, '속초보광병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (133, '속초우리장례식장(휴업)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (134, '송도하나장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (135, '송산장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (136, '송산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (137, '세일장례식장(구.복사골)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (138, '송정장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (139, '송현장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (140, '수성메트로병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (141, '수성연도실');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (142, '수원시연화장장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (143, '수성요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (144, '세화병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (145, '센텀장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (146, '수원요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (147, '수장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (148, '순창군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (149, '순창온누리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (150, '순창요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (151, '순천의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (152, '순창장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (153, '송원장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (154, '송정사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (155, '순천향대학병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (156, '순천중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (157, '순천한국병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (158, '순천향부천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (159, '순천향장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (160, '순천향천안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (161, '순창현대장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (162, '숭례관장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (163, '쉴낙원 남대전장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (164, '쉴낙원경기장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (165, '쉴낙원 오산동탄 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (166, '쉴낙원 당진 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (167, '쉴낙원갈마성심장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (168, '쉴낙원김포장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (169, '쉴낙원서울장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (170, '스카이장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (171, '시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (172, '시영의료재단 영동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (173, '시티병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (174, '시티장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (175, '시흥누리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (176, '시흥우리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (177, '쉴낙원인천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (178, '시흥장례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (179, '송탄장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (180, '신가병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (181, '송탄중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (182, '송학주천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (183, '신광천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (184, '신세계병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (185, '신정장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (186, '신천연합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (187, '신천제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (188, '신풍장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (189, '신협서해병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (190, '신화장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (191, '신태인장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (192, '실로암사랑요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (193, '아너스힐병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (194, '씨티장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (195, '아산유리요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (196, '아성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (197, '신평장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (198, '아산충무병원 국화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (199, '아주대학병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (200, '안강중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (201, '안동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (202, '아주조은요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (203, '안동의료원 장례식장 국화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (204, '안동농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (205, '안산온누리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (206, '안동전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (207, '안산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (208, '안심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (209, '안양메트로병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (210, '안양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (211, '양구군장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (212, '양산서울요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (213, '양산시민장례호텔');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (214, '양산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (215, '시화병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (216, '양서농협장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (217, '양수삼성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (218, '안중장례문화센타');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (219, '양주한국병원장례문화원 주식회사');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (220, '양양장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (221, '양주소망장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (222, '양주장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (223, '양지요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (224, '양천효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (225, '양평 갈월장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (226, '양평병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (227, '양평장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (228, '언양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (229, '에스병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (230, '에스엘 부평지점 세림병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (231, '엠마오사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (232, '안계농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (233, '안덕장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (234, '엠마우스병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (235, '엠지(MG)새마을금고 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (236, '여수강남요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (237, '여수보람장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (238, '여수제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (239, '여수장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (240, '여의도성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (241, '여주시민장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (242, '여주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (243, '여천전남병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (244, '연세대학교 강남장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (245, '여천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (246, '연세대학교 신촌장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (247, '연세대학교 용인장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (248, '연세대학교 원주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (249, '여수전남병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (250, '연세에스병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (251, '연세병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (252, '연세장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (253, '연세요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (254, '연수송도장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (255, '연천군장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (256, '영광농협장례식장(영광낙원장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (257, '영광종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (258, '영광장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (259, '영남대학교의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (260, '영남제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (261, '영덕아산병원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (262, '영덕제일요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (263, '영덕전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (264, '영덕효요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (265, '영등포장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (266, '영동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (267, '영동장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (268, '영동제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (269, '영락원전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (270, '영북농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (271, '영산포농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (272, '영산포제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (273, '영산요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (274, '영암군산림조합추모관');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (275, '영암농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (276, '영암장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (277, '영암효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (278, '영양전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (279, '영월장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (280, '영주 국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (281, '영주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (282, '영주적십자병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (283, '영천영락원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (284, '영천국화원전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (285, '울산영락원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (286, '우리요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (287, '우리병원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (288, '울산하늘공원(장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (289, '울산전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (290, '울진군의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (291, '웅상중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (292, '웅천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (293, '원광대학교병원장례문화원(천도장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (294, '원광종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (295, '원당연세장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (296, '원당장례식장(주)문베스트');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (297, '원병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (298, '원자력병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (299, '원주의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (300, '원진녹색병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (301, '웰니스1004병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (302, '월명장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (303, '위더스요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (304, '유림장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (305, '유성선병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (306, '유한회사보람');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (307, '은하수공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (308, '음성농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (309, '온양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (310, '의)증평장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (311, '의령사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (312, '의성중부농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (313, '의정부성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (314, '유성한가족병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (315, '윤서병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (316, '은평요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (317, '의정부을지대학교병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (318, '의정부장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (319, '이담 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (320, '이대목동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (321, '이대서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (322, '이래인장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (323, '의성전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (324, '의성제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (325, '이로운요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (326, '이인농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (327, '인월장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (328, '인제대학교상계백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (329, '인제장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (330, '인창병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (331, '의령전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (332, '의성성심요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (333, '인천가족공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (334, '인천광역시의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (335, '인천기독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (336, '인천사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (337, '인천삼성장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (338, '인천백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (339, '인천성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (340, '인천적십자병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (341, '인천힘찬종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (342, '인하대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (343, '일곡병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (344, '일산백장례서비스(주)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (345, '일산복음병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (346, '일산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (347, '임실 중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (348, '자굴산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (349, '자연병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (350, '자인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (351, '자인전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (352, '장곡농협홍주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (353, '장례식장상예원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (354, '장성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (355, '장례식장 평화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (356, '장유누가병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (357, '장호원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (358, '장흥병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (359, '장흥우리병원중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (360, '전곡효사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (361, '전남대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (362, '전북대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (363, '전주고려병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (364, '전남중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (365, '전주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (366, '전주시민장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (367, '임실군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (368, '정다운병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (369, '정다운장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (370, '정선군사북장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (371, '정병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (372, '정선병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (373, '정선장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (374, '정요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (375, '정원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (376, '정읍사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (377, '정읍아산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (378, '제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (379, '정읍장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (380, '정읍장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (381, '정다운 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (382, '정읍호남장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (383, '제일장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (384, '제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (385, '제주그린장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (386, '제일조은병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (387, '제주대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (388, '제주의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (389, '제천노인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (390, '제천서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (391, '제천세종장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (392, '제천제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (393, '장수군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (394, '조선대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (395, '조치원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (396, '제일효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (397, '좋은삼정병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (398, '조은금강병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (399, '조암장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (400, '주문진장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (401, '주식회사구민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (402, '주식회사정겨운(우신장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (403, '주식회사 헤븐앤어스');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (404, '주식회사하늘정원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (405, '정산미당장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (406, '중앙U병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (407, '중앙대학교광명병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (408, '중앙대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (409, '중앙병원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (410, '중앙요양병원 장례식장(구.가야기독)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (411, '중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (412, '증평장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (413, '증평현대장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (414, '진도군산림조합직영추모관장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (415, '지샘병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (416, '증평대한장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (417, '진교장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (418, '중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (419, '진도장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (420, '진보병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (421, '진부장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (422, '진도전남병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (423, '진안군의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (424, '진영전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (425, '진주시민장례식장 (주)휴드림');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (426, '진영병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (427, '진주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (428, '진천제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (429, '진주중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (430, '차병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (431, '진천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (432, '주식회사 건양대부여장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (433, '참사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (434, '참사랑장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (435, '참조은요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (436, '창녕군공설장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (437, '창녕전문 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (438, '창선공익장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (439, '창원경상대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (440, '창녕효요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (441, '창원시립상복공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (442, '창원파티마병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (443, '창원한마음병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (444, '천안삼거리국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (445, '천안의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (446, '천안충무병원 국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (447, '천안하늘공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (448, '천안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (449, '천주성삼병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (450, '철원병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (451, '철원장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (452, '첨단요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (453, '청구성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (454, '청기와장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (455, '청기와장례식장(계양점)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (456, '청송군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (457, '청십자병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (458, '청양농협 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (459, '청양훈병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (460, '청주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (461, '청주성모병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (462, '청주시장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (463, '청주의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (464, '청주탑요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (465, '초정유진 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (466, '청하요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (467, '추모원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (468, '추병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (469, '춘천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (470, '충남대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (471, '충남보령아산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (472, '춘해병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (473, '충주기독장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (474, '충주병원장례식장(주)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (475, '충주영광장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (476, '충주의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (477, '춘추장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (478, '충북대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (479, '충효경주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (480, '칠곡경북대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (481, '코리아병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (482, '큰길장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (483, '칠곡군농협연합장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (484, '케이마디병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (485, '큰사랑요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (486, '태릉성심장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (487, '태백문화장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (488, '탄금장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (489, '태안군보건의료원 상례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (490, '태찬장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (491, '파주보람장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (492, '파주성모요양병원부설장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (493, '통영서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (494, '통영전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (495, '파라밀장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (496, '평창군장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (497, '포천장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (498, '포항국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (499, '포항e병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (500, '포항성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (501, '포항시민전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (502, '포항세명기독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (503, '포항제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (504, '풍기성심요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (505, '풍기전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (506, '프라임장례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (507, '플러스단원병원장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (508, '하귀농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (509, '하나원전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (510, '하나장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (511, '하남성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (512, '하남시 마루공원(장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (513, '하늘공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (514, '하늘원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (515, '하늘원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (516, '하늘재전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (517, '하늘전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (518, '하동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (519, '하동우리들병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (520, '하동장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (521, '학교법인 원불교대학원 모현장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (522, '하양전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (523, '학교법인영산학원 산본장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (524, '학교법인영산학원시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (525, '한강성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (526, '한결장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (527, '한국병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (528, '한국보훈복지의료공단중앙보훈병원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (529, '한길장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (530, '한도병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (531, '한국장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (532, '한독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (533, '한림대동탄성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (534, '한림대 강남성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (535, '한림대성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (536, '한림병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (537, '한림정낭장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (538, '한마음병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (539, '한마음효장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (540, '한별장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (541, '한사랑병원장례문화센타');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (542, '한성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (543, '한솔장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (544, '한양대학교구리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (545, '한사랑요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (546, '한서장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (547, '한양대학병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (548, '한일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (549, '한중프라임장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (550, '한패밀리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (551, '함안하늘공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (552, '함양성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (553, '함양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (554, '함양제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (555, '함열장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (556, '함평농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (557, '함평성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (558, '함평장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (559, '합덕장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (560, '합천고려병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (561, '합천추모공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (562, '해남종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (563, '해남현대장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (564, '해성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (565, '해운대백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (566, '해남국제장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (567, '해동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (568, '해남군 산림조합장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (569, '해남우리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (570, '해남장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (571, '행림병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (572, '행복한병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (573, '현대S라이프(주)연세병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (574, '허병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (575, '현대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (576, '헤아림장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (577, '현대장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (578, '혜민병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (579, '현대장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (580, '혜성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (581, '혜인요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (582, '혜원성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (583, '호남장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (584, '호반병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (585, '홍성의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (586, '홍성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (587, '홍성추모공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (588, '홍익병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (589, '홍천군장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (590, '홍천아산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (591, '홍천장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (592, '화성장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (593, '화성중앙종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (594, '화성함백산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (595, '화순장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (596, '화순전남대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (597, '화천군공설장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (598, '황금요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (599, '회천농협장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (600, '횡성삼성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (601, '횡성장례문화센터');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (602, '황산장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (603, '효경G병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (604, '효사랑요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (605, '효사랑장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (606, '효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (607, '효성병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (608, '효산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (609, '효성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (610, '효사랑장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (611, '효신전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (612, '효원장례문화센타');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (613, '효자원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (614, '효자장례타운');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (615, '휴앤유병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (616, '흥덕장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (617, '흥해경희요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (618, '희망병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (619, '희윤요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (620, '광탄현대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (621, '괴산동부장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (622, '괴산성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (623, '괴정병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (624, '괴산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (625, '교원예움 평택장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (626, '교하장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (627, '구례병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (628, '구미가톨릭요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (629, '구로성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (630, '구례효사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (631, '구룡장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (632, '구리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (633, '구미장례식장해원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (634, '구미제일요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (635, '구미천사요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (636, '구미푸른요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (637, '광적장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (638, '구호전장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (639, '국립중앙의료원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (640, '국민건강보험공단일산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (641, '국민요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (642, '국민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (643, '국제성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (644, '국화원문경장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (645, '국화향기');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (646, '군산의료원장례식장 오행원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (647, '군자장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (648, '군산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (649, '군위농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (650, '굿뉴스요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (651, '굿모닝병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (652, '규암농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (653, '그랜드중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (654, '그랜드부민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (655, '그린장례문화원주식회사');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (656, '근로복지공단 인천병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (657, '근로복지공단 태백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (658, '구병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (659, '광주기독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (660, '근로복지공단대전병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (661, '금강병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (662, '금강쉴낙원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (663, '금강장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (664, '금사장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (665, '금송장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (666, '금호장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (667, '기장병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (668, '길병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (669, '김녕농협 장례문화센터');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (670, '김제 중앙병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (671, '김제우석병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (672, '김제장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (673, '김천시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (674, '김천제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (675, '김천요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (676, '김천의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (677, '김해시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (678, '김화장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (679, '김해전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (680, '김해한솔병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (681, '나눔병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (682, '나주예림장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (683, '나주애향장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (684, '나주한국병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (685, '나주효사랑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (686, '나진장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (687, '낙원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (688, '남구미요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (689, '남악장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (690, '나주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (691, '나주종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (692, '나주중앙요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (693, '남도장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (694, '남양주장례식장(구 남양동산)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (695, '남동스카이장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (696, '남양주국민병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (697, '남양주한양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (698, '남원의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (699, '남울산보람국화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (700, '남원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (701, '남지요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (702, '남천안 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (703, '남천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (704, '남해병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (705, '(주)비이케이더블유 좋은삼선병원지점');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (706, '남해추모누리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (707, '노원을지대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (708, '(주)서원 바른장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (709, '(주)세종병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (710, '남해전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (711, '녹동농협 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (712, '논산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (713, '놀뫼시민장례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (714, '녹동현대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (715, '농협연합장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (716, '녹십자요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (717, '뉴고려병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (718, '농협장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (719, '뉴타운장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (720, '늘푸른장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (721, '다니엘병원장례식장(구 늘푸른장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (722, '다대수병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (723, '기독장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (724, '다보스병원장례식장(영문의료재단)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (725, '다사랑중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (726, '다인농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (727, '단국대학교병원 천안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (728, '단양군립노인요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (729, '단양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (730, '담양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (731, '담양동산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (732, '담양제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (733, '당진중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (734, '당진종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (735, '대구가톨릭대학교의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (736, '대구기독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (737, '대구병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (738, '대구보훈병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (739, '대구시민전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (740, '대구의료원 국화원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (741, '대구요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (742, '대구파티마병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (743, '대동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (744, '대구전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (745, '대성장례센터');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (746, '대소장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (747, '대성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (748, '대송장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (749, '대연장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (750, '대전보훈병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (751, '대영장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (752, '대전선병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (753, '대전을지대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (754, '대전장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (755, '대청병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (756, '대한병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (757, '대천역전장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (758, '대한장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (759, '대한적십자사상주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (760, '더원실업 우란장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (761, '도리안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (762, '도민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (763, '더조은장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (764, '독산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (765, '대우병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (766, '도계장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (767, '대전갈마장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (768, '동강병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (769, '동국대학교경주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (770, '동광양장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (771, '동국대학교일산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (772, '동두천중앙성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (773, '동래봉생병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (774, '동군산병원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (775, '동남권원자력의학원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (776, '동두천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (777, '동래한서병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (778, '동마산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (779, '동부요양병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (780, '동산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (781, '동서천 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (782, '동수원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (783, '동신병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (784, '동아대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (785, '동안산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (786, '동의의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (787, '동인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (788, '동일죽장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (789, '동전주 장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (790, '동주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (791, '동창원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (792, '동백장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (793, '동해전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (794, '드림병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (795, '마량장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (796, '마송장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (797, '만평장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (798, '동해동인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (799, '동해병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (800, '메디힐병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (801, '맑은샘병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (802, '메디인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (803, '메디팜병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (804, '메디힐장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (805, '메리놀병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (806, '면목녹색병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (807, '명덕효요양병원부속백화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (808, '명품병원장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (809, '모레아장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (810, '목포기독병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (811, '목포봉황장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (812, '목포성심장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (813, '목포시의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (814, '목포장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (815, '목포현대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (816, '무안제일병원 무안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (817, '무안초당병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (818, '무주군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (819, '문경장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (820, '문경제일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (821, '문산장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (822, '문산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (823, '동아메디병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (824, '목포하당장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (825, '문요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (826, '미루병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (827, '밀양시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (828, '밀양농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (829, '바른병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (830, '밀양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (831, '반송장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (832, '배방장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (833, '배성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (834, '백년장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (835, '백병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (836, '백제병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (837, '백악관장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (838, '백제장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (839, '벌교삼성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (840, '법성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (841, '벌교장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (842, '벌교중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (843, '보람김해장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (844, '보람상조개발(주)양산부산대병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (845, '보람의정부장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (846, '보람인천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (847, '보람상조라이프(주)천안국빈장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (848, '보성아산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (849, '보정장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (850, '보은성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (851, '복음병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (852, '보성우리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (853, '보성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (854, '보은농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (855, '보은요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (856, '보은장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (857, '복지장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (858, '봉담장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (859, '봉동호스피스장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (860, '봉생병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (861, '부곡온천병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (862, '봉화군산림조합장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (863, '부림요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (864, '봉화장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (865, '부산광역시의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (866, '부산대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (867, '부산백병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (868, '부산보훈병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (869, '부산성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (870, '부산영락공원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (871, '베스트장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (872, '별그리다(사담재)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (873, '부산전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (874, '부안호남장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (875, '부성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (876, '부안효병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (877, '부천성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (878, '분당서울대학교병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (879, '부천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (880, '북신안농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (881, '분당제생병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (882, '비에스종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (883, '분당차병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (884, '빛가람종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (885, '빛가람장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (886, '빛 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (887, '사랑의병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (888, '사비장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (889, '사하구민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (890, '사천공설장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (891, '사천시농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (892, '사천중앙요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (893, '산림조합 장성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (894, '산청경호장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (895, '산청장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (896, '삼봉장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (897, '영천참좋은요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (898, '예담장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (899, '예산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (900, '예드림장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (901, '예산명지병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (902, '예산종합병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (903, '예지 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (904, '예지원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (905, '예천권병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (906, '영양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (907, '예천농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (908, '예천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (909, '오산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (910, '오산한국병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (911, '오수장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (912, '오천삼성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (913, '오포장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (914, '옥천농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (915, '옥당장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (916, '옥천성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (917, '옥산전문장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (918, '온고을장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (919, '온누리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (920, '온종합병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (921, '옥곡장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (922, '완도대성병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (923, '왜관병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (924, '용문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (925, '완도장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (926, '용상안동병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (927, '용원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (928, '용인 평온의 숲장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (929, '용인제일메디장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (930, '용인서울병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (931, '용인시민장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (932, '우리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (933, '우주장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (934, '우리하늘장례원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (935, '우선종합(주)장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (936, '우수영장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (937, '운경의료재단곽병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (938, '울산국화원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (939, '울산대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (940, '운정장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (941, '울산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (942, '울릉군보건의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (943, '울산시티병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (944, '우리병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (945, '(주)시민장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (946, '(유)동이리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (947, '(주)안면도장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (948, '(주)영천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (949, '(주)영천장례식장(영남대학교영천병원지점)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (950, '(주)울산국화원장례식장 북울산지점');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (951, '(주)원지산청장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (952, '(주)장례식장아시아드 ');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (953, '(주)제이엔에이실업');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (954, '(주)중앙병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (955, '(주)착한전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (956, '(주)예담 활주로장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (957, '(주)천지문화원 (천지장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (958, '(주)코스모스제일장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (959, '(주)한국효려(한국병원장례식장)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (960, '(주)한빛장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (961, '(주)합천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (962, '21C한일병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (963, 'BHS한서병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (964, 'SMG연세병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (965, 'DS병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (966, 'Sh수협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (967, 'e좋은병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (968, 'k병원장례식장 예지원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (969, '㈜영산포한우리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (970, '가남베스트장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (971, '가야장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (972, '가톨릭대학교 은평성모장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (973, '가톨릭대학교대전성모병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (974, '가평군농협효문화센터');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (975, '가평연새장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (976, '갑을장유병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (977, '강경장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (978, '강남병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (979, '강동경희대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (980, '감곡장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (981, '갑을녹산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (982, '강동성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (983, '강릉동인병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (984, '강릉아나병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (985, '강릉아산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (986, '강북휴요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (987, '강북장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (988, '강북전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (989, '강산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (990, '강서개화장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (991, '강서장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (992, '강서중앙장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (993, '강원대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (994, '강원도강릉의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (995, '강원도속초의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (996, '강원도영월의료원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (997, '강원효장례식장/문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (998, '(유)무안병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (999, '(유)브이아이피장례타운');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1000, '강진군산림조합추모관장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1001, '강진영락장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1002, '강진의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1003, '강진장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1004, '강화병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1005, '강화장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1006, '거금장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1007, '거창서경병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1008, '거창적십자병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1009, '거제백병원농협장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1010, '거창장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1011, '건국대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1012, '(유)성인천장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1013, '건국대학교충주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1014, '건양대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1015, '검단탑병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1016, '경기도의료원 수원병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1017, '경기도의료원 안성병원장례식장(휴업)');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1018, '경기도의료원 의정부병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1019, '경기도의료원 이천병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1020, '경기도의료원 파주병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1021, '경기도의료원 포천병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1022, '경남도립노인전문병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1023, '경남요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1024, '경북대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1025, '경산장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1026, '경산중앙병원장례예식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1027, '경상국립대학교병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1028, '경상남도 마산의료원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1029, '경상북도포항의료원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1030, '경주전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1031, '경안장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1032, '경찰병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1033, '경주하늘마루장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1034, '경희병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1035, '경희의료원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1036, '계명대학교경주동산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1037, '계룡장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1038, '계명대학교대구동산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1039, '계명대학교동산병원백합원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1040, '고려대구로병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1041, '고금번영회장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1042, '고려대안산병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1043, '고려대학교안암병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1044, '고덕장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1045, '고려병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1046, '고려장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1047, '고령영생병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1048, '고령대가야장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1049, '고령전문장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1050, '고성장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1051, '고성장례식장화라주식회사');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1052, '고색의료재단 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1053, '고성제일요양병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1054, '고성성심병원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1055, '고성영락원장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1056, '고신대병원 장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1057, '고아농협 장례문화원');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1058, '고인돌장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1059, '고전장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1060, '고창우리장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1061, '곡성옥과장례식장');
INSERT INTO facilities.funeral (id, 장례식장명) VALUES (1062, '공생병원장례식장');
